// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tarea4.Migrations
{
    [DbContext(typeof(VideoJuegosContext))]
    [Migration("20241019232002_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ClasePersonaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmaFavorita")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoDelPersonaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Habilidad")
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelDePoder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriePeliculaLibroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("constructor_videojuegosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("constructor_videojuegosId");

                    b.ToTable("ColecciondeEntidadesClasePersonajes");
                });

            modelBuilder.Entity("ClaseVideoJuegos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desarrollador")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDeLanzamiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenDePortada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plataforma")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ColecciondeEntidadesClaseVideoJuegos");
                });

            modelBuilder.Entity("ClasePersonaje", b =>
                {
                    b.HasOne("ClaseVideoJuegos", "constructor_videojuegos")
                        .WithMany("nommbreDeLista_Personajes")
                        .HasForeignKey("constructor_videojuegosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("constructor_videojuegos");
                });

            modelBuilder.Entity("ClaseVideoJuegos", b =>
                {
                    b.Navigation("nommbreDeLista_Personajes");
                });
#pragma warning restore 612, 618
        }
    }
}
