// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tarea4.Migrations
{
    [DbContext(typeof(VideoJuegosContext))]
    partial class VideoJuegosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ClasePersonaje", b =>
                {
                    b.Property<int>("Id_personaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArmaFavorita")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClaseVideoJuegosId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FotoDelPersonaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Habilidad")
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelDePoder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_personaje");

                    b.HasIndex("ClaseVideoJuegosId");

                    b.ToTable("ColecciondeEntidadesClasePersonajes");
                });

            modelBuilder.Entity("ClasePlataformas", b =>
                {
                    b.Property<int>("Id_Plataformas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombredelaplataforma")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Plataformas");

                    b.ToTable("ColecciondeEntidadesClasePlataforma");
                });

            modelBuilder.Entity("ClaseVideoJuegos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desarrollador")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDeLanzamiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenDePortada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plataforma")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ColecciondeEntidadesClaseVideoJuegos");
                });

            modelBuilder.Entity("ClasePersonaje", b =>
                {
                    b.HasOne("ClaseVideoJuegos", null)
                        .WithMany("nommbreDeLista_Personajes")
                        .HasForeignKey("ClaseVideoJuegosId");
                });

            modelBuilder.Entity("ClaseVideoJuegos", b =>
                {
                    b.Navigation("nommbreDeLista_Personajes");
                });
#pragma warning restore 612, 618
        }
    }
}
